name: pyprojectr-ci

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13, 3.14, 3.15]
    steps:
      - uses: actions/checkout@v6
        name: checkout
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: install
        run: |
          pip install tox
          tox -e py
